<?php
declare(strict_types=1);
require_once __DIR__.'/../config/app.php';require_once APP_ROOT.'/core/auth.php';$user=require_auth();$pdo=db();$classId=(int)($_GET['id']??0);
$stmt=$pdo->prepare('SELECT * FROM classes WHERE id=?');$stmt->execute([$classId]);$class=$stmt->fetch();if(!$class){http_response_code(404);exit('Turma não encontrada.');}
if($user['role']==='teacher'&&!teacher_has_class((int)$user['id'],$classId)){http_response_code(403);require APP_ROOT.'/partials/403.php';exit;}
$stmt=$pdo->prepare("SELECT s.id,s.name,s.enrollment,s.active FROM students s JOIN class_students cs ON cs.student_id=s.id WHERE cs.class_id=? ORDER BY s.name");$stmt->execute([$classId]);$students=$stmt->fetchAll();
if($user['role']==='admin'){$stmt=$pdo->prepare("SELECT e.id,e.title,e.created_at,u.name teacher_name,s.name subject_name,(SELECT COUNT(*) FROM results r WHERE r.exam_id=e.id) corrected FROM exams e JOIN users u ON u.id=e.teacher_id JOIN subjects s ON s.id=e.subject_id WHERE e.class_id=? ORDER BY e.created_at DESC");$stmt->execute([$classId]);}
else{$stmt=$pdo->prepare("SELECT e.id,e.title,e.created_at,u.name teacher_name,s.name subject_name,(SELECT COUNT(*) FROM results r WHERE r.exam_id=e.id) corrected FROM exams e JOIN users u ON u.id=e.teacher_id JOIN subjects s ON s.id=e.subject_id WHERE e.class_id=? AND e.teacher_id=? ORDER BY e.created_at DESC");$stmt->execute([$classId,$user['id']]);}
$exams=$stmt->fetchAll();
$pageTitle=$class['name'];require APP_ROOT.'/partials/header.php';
?>
<div class="page-toolbar reveal"><div><a class="back-link" href="<?= e(url('classes/index.php')) ?>">← Voltar</a><span class="eyebrow">TURMA • <?= (int)$class['school_year'] ?></span><h2><?= e($class['name']) ?></h2><p><?= count($students) ?> alunos matriculados<?= $class['grade_level']?' • '.e($class['grade_level']):'' ?></p></div><div class="hero-actions"><?php if($user['role']==='admin'): ?><a class="btn btn-soft" href="<?= e(url('classes/manage.php?id='.$classId)) ?>">⚙ Gerenciar</a><?php endif; ?><a class="btn btn-primary" href="<?= e(url('exams/create.php?class='.$classId)) ?>">+ Criar prova</a></div></div>
<div class="dashboard-grid"><section class="panel reveal"><div class="panel-head"><div><span class="eyebrow">ESTUDANTES</span><h3>Lista da turma</h3></div><span class="count-pill"><?= count($students) ?> alunos</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Aluno</th><th>Matrícula</th><th>Status</th></tr></thead><tbody><?php foreach($students as $s): ?><tr><td data-label="Aluno"><div class="person-cell"><div class="avatar small soft"><?= e(mb_strtoupper(mb_substr($s['name'],0,1))) ?></div><strong><?= e($s['name']) ?></strong></div></td><td data-label="Matrícula"><code class="code-pill"><?= e($s['enrollment']) ?></code></td><td data-label="Status"><span class="status-dot <?= (int)$s['active']?'on':'off' ?>"></span><?= (int)$s['active']?'Ativo':'Inativo' ?></td></tr><?php endforeach; ?></tbody></table></div></section>
<aside class="panel reveal delay-1"><div class="panel-head"><div><span class="eyebrow">AVALIAÇÕES</span><h3>Provas da turma</h3></div></div><?php if(!$exams): ?><div class="empty-state small"><div class="empty-icon">✓</div><p>Nenhuma prova criada ainda.</p></div><?php else: ?><div class="simple-list"><?php foreach($exams as $e): ?><a class="simple-list-item link" href="<?= e(url('exams/view.php?id='.$e['id'])) ?>"><div><strong><?= e($e['title']) ?></strong><span><?= e($e['subject_name']) ?> • <?= date('d/m/Y',strtotime($e['created_at'])) ?></span></div><div class="right-meta"><b><?= (int)$e['corrected'] ?></b><span>corrigidos</span></div></a><?php endforeach; ?></div><?php endif; ?></aside></div>
<?php require APP_ROOT.'/partials/footer.php'; ?>
